development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/trademark_order/payment_confirmation"
  email: thiagotnunes@yahoo.com.br

test:
  <<: *development

production:
  authenticity_token: 18E50F3027B74AD6A7340CF9056E2678
  email: thiagotnunes@yahoo.com.br
  return_to: "/trademark_order/payment_confirmation"
